# Cassandra
cassandra:
  build: ./cassandra
  container_name: cassandra_container
  expose:
    - "9042"
  ports:
    - "9042:9042"

# SkillDirectory
skilldirectory:
  build: .
  container_name: skilldirectory_container
  environment:
    - CASSANDRA_URL=172.17.0.2
    - CASSANDRA_PORT=9042
    - CASSANDRA_KEYSPACE=skill_directory_keyspace
  expose:
    - "8080"
  ports:
    - "8080:8080"
