#!/bin/bash

TEST_RESPONSES=()
WHITELIST=()
THRESHOLD=80
COVERAGE=true
MODULES=""
ALL=false

function run_tests {
  for module in $MODULES; do
    res="$(go test $module --cover)"
    echo $res
    TEST_RESPONSES+=("$res")
  done
}

function all_passed {
  for res in "${TEST_RESPONSES[@]}"; do
    if [ $(echo $res | grep -o FAIL | wc -w | xargs echo) != 0 ]; then
      return 1
    fi
  done
  return 0
}

function above_threshold {
  for res in "${TEST_RESPONSES[@]}"; do
    is_whitelist=false;
    my_module=$(echo $res | awk '{print $2}')
    for module in $WHITELIST; do
      if [ ${my_module#*\/} == ${module#*\/} ]; then
        is_whitelist=true
      fi
    done
    if ! $is_whitelist; then
      if [ $(echo $res | grep -o '[0-9\.]*%' | sed "s/%/ < $THRESHOLD/" | bc) != 0 ]; then
        return 1
      fi
    fi
  done
  return 0
}

while (( "$#" )); do
  case "$1" in
    -a|--all)
      ALL=true
      shift
      ;;
    -m|--module)
      MODULES="$MODULES $2"
      if ! $COVERAGE; then
        WHITELIST+=(`echo $2`)
      fi
      shift 2
      ;;
    -w|--whitelist)
      COVERAGE=false
      shift
      ;;
    -t|--threshold)
      THRESHOLD=$2
      shift 2
      ;;
    *)
      echo "Unknown flag $1"
      exit 127
  esac
done

if $ALL; then
  MODULES=$(glide nv)
fi

run_tests
all_passed && above_threshold
